config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  namespace :admin do
    resources :products
    resources :carts
    resources :orders
    resources :users
  end

  devise_for :users

  root 'welcome#index'

  resources :products
  resources :carts
  resources :cart_items
  resources :orders

  # static pages
  get '/privacy_policy', to: 'welcome#privacy_policy', as: :privacy_policy
  get '/terms', to: 'welcome#terms', as: :terms_and_conditions
  get '/refund_policy', to: 'welcome#refund_policy', as: :refund_policy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_paper_trail

  belongs_to :user, inverse_of: :carts

  has_many :cart_items, inverse_of: :cart, dependent: :destroy
  has_one :order, inverse_of: :cart, dependent: :destroy

  enum delivery_method: { by_air: 0 }
  enum region: {
    greater_accra_region: 0,
    ashanti_region: 1,
    brong_ahafo_region: 2,
    central_region: 3,
    eastern_region: 4,
    northern_region: 5,
    upper_east_region: 6,
    upper_west_region: 7,
    volta_region: 8,
    western_region: 9
  }

  def add_cart_item(cart_item_params)
    # TODO: Fetch unit_price, weight and dimensions via ZincAPI and
    # override them in cart_item_params in order to prevent hackers from
    # crafting cart_items with lower prices, weight or dimensions than
    # actually specified on Amazon

    item = cart_items.find_by(product_id: cart_item_params[:product_id],
                              retailer: cart_item_params[:retailer])

    cart_item_params[:quantity] = 1

    if item
      cart_item_params[:quantity] += 1
      item.update!(cart_item_params)
      return item
    end

    cart_items.create!(cart_item_params)
  end
end

app/controllers/admin/carts_controller.rb
# frozen_string_literal: true

class Admin::CartsController < AdminController
  before_action :set_cart, only: %i[show edit update destroy]

  # GET /carts
  def index
    @carts = Cart.all.order(created_at: :desc)
  end

  # GET /carts/1
  def show; end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit; end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)

    if @cart.save
      redirect_to admin_cart_path(@cart), notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /carts/1
  def update
    if @cart.update(cart_params)
      redirect_to admin_cart_path(@cart), notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    redirect_to admin_carts_url, notice: 'Cart was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.require(:cart).permit(:archived)
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_cart

  # GET /carts/1
  def show; end

  def edit; end

  # PATCH/PUT /carts/1
  def update
    if @cart.update(cart_params)
      redirect_to new_order_path
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = current_cart
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.require(:cart).permit(:full_name,
                                 :address,
                                 :region,
                                 :city_or_town,
                                 :phone_number)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/admin/carts/_form.html.erb
<%= form_with(model: [:admin, cart], local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :archived %>
    <%= form.check_box :archived %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', admin_cart_path(@cart) %> |
<%= link_to 'Back', admin_carts_path %>

app/views/admin/carts/index.html.erb
<div class="container">

  <div class="row mt-3">

    <div class="col-md-12">

      <h3>Admin / Carts</h3>
      <hr>

      <% @carts.each do |cart| %>
        <div class="card mb-4">
          <div class="card-header">
            <div class="d-flex w-100 justify-content-between flex-wrap">
              <div>Cart Created: <%= cart.created_at.to_date.to_s(:long) %></div>
              <div>Total: <%= number_to_currency_gh dollar_to_cedi ShippingCalculator.new(cart).order_total %></div>
              <div>Ship To: <%= "#{cart.user.full_name} <#{cart.user.email}>" %></div>
              <div>
                <a href="<%= admin_cart_path cart %>">Cart Details</a>
              </div>
            </div>
          </div>

          <ul class="list-group list-group-flush">
            <% cart.cart_items.order(created_at: :desc).each do |cart_item| %>
              <li class="list-group-item d-flex flex-column w-100 justify-content-start px-2">
                <a href="<%= admin_product_path cart_item.product %>">
                  <div class="d-flex w-100 justify-content-start">
                    <img class="product-image mr-2" src="<%= cart_item.product.main_image %>" width="100" style="height: 100px">
                    <div>
                      <h6 class="mb-2"><%= truncate cart_item.product.title, length: 60 %></h6>
                      <div class="text-danger ml-auto mb-2"><%= number_to_currency_gh dollar_to_cedi cart_item.unit_price %></div>
                      <div>Qty: <%= cart_item.quantity %></div>
                    </div>
                  </div>
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', admin_carts_path %>

app/views/admin/carts/show.html.erb
<div class="container">

  <div class="row mt-3">

    <div class="col-lg-4 order-lg-1">
      <%= render(layout: 'carts/costs_card', locals: {
          shippingCalculator: ShippingCalculator.new(@cart)
      }) do %>

        <%= link_to 'Edit', edit_admin_cart_path(@cart), class: 'btn btn-block btn-accent' %>
        <%= link_to 'Delete Cart', admin_cart_path(@cart), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-block btn-danger' %>
        <%= link_to 'Back', admin_carts_path, class: 'btn btn-block btn-info' %>
      <% end %>
    </div>

    <div class="col-lg-8">
      <p class="ml-2 mb-2 lead">
        <%= @cart.user.full_name %>, <%= @cart.user.email %>,
        tel: <%= @cart.user.phone_number %>
      </p>
      <ul class="list-group mb-4">
        <% @cart.cart_items.order(created_at: :desc).each do |cart_item| %>
          <li class="list-group-item d-flex flex-column w-100 justify-content-start px-2">
            <a href="<%= admin_product_path cart_item.product %>">
              <div class="d-flex w-100 justify-content-start mb-2">
                <img class="product-image mr-3" src="<%= cart_item.product.main_image %>" width="100" style="height: 100px">
                <div>
                  <h6 class="mb-1"><%= truncate cart_item.product.title, length: 60 %></h6>

                  <div class="text-danger ml-auto"><%= number_to_currency cart_item.unit_price %></div>
                  <div>Qty: <%= cart_item.quantity %></div>
                </div>
              </div>
            </a>

            <div class="d-flex w-100 justify-content-end">
            </div>
          </li>
        <% end %>
      </ul>
    </div>

  </div>

</div>