config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  namespace :admin do
    resources :products
    resources :carts
    resources :orders
    resources :users
  end

  devise_for :users

  root 'welcome#index'

  resources :products
  resources :carts
  resources :cart_items
  resources :orders

  # static pages
  get '/privacy_policy', to: 'welcome#privacy_policy', as: :privacy_policy
  get '/terms', to: 'welcome#terms', as: :terms_and_conditions
  get '/refund_policy', to: 'welcome#refund_policy', as: :refund_policy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

# Create two columns api status and api hash
# Use those two columns to query the status of the order

class Order < ApplicationRecord
  has_paper_trail

  include ActionView::Helpers::NumberHelper

  belongs_to :user, inverse_of: :orders
  belongs_to :cart, inverse_of: :order

  enum status: { paid: 0,
                 bought: 1,
                 received_at_warehouse: 3,
                 shipped_to_ghana: 4,
                 received_in_ghana: 5,
                 delivered_to_client: 6 }
  
  enum api_status: {
    pending: 7,
    aborted: 8,
    account_locked_verification_required: 9,
    success: 10
  }

  def purchase; end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

class Admin::OrdersController < AdminController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders
  def index
    @orders = Order.all.order(created_at: :desc)
  end

  # GET /orders/1
  def show
    @shipping_cart = ShippingCalculator.new(@order.cart)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to admin_order_path(@order), notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to admin_order_path(@order), notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to admin_orders_url, notice: 'Order was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:archived, :status)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[show]

  # GET /orders
  def index
    @orders = current_user.orders.all.order(created_at: :desc)
  end

  # GET /orders/1
  def show
    @shipping_cart = ShippingCalculator.new(@order.cart)
  end

  # GET /orders/new
  def new
    @order = current_cart.build_order
  end

  # POST /orders
  def create
    @order = current_cart.build_order(order_params)
    @order.user = current_user

    if RavePayVerifier.new(current_cart).paid?(order_params[:txtref]) == false
      flash.now[:alert] = 'There was an issue while trying to process your payment.'
      render(:new) && return
    end

    @order.cart.update!(paid_at: Time.current)
    builder = OrderBuilder.new @order
    builder.get_retailers
    zinc_api = Zinc.new
    request_ids = zinc_api.place_order builder.get_request_body
    @order.api_hash = request_ids
    @order.api_status = 7
    @order.save!
    redirect_to @order, notice: 'Order was placed successfully.', flash: { thanks_for_shopping_with_us: true }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = current_user.orders.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:txtref)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-check">
    <%= form.check_box :archived, class: 'form-check-input' %>

    <%= form.label :archived, class: 'form-check-label' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status,
                    choices = Order.statuses.keys.map { |w| [w.titleize, w] },
                    options = {
                        include_blank: false
                    },
                    html_options = {
                        class: "form-control"
                    } %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-accent btn-block" %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<div class="container">

  <div class="row mt-3">

    <div class="col-md-8 mx-auto">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">
            Editing Order
          </h5>

          <%= render 'form', order: @order %>
        </div>
        <div class="card-body">
          <%= link_to 'Show', admin_order_path(@order), class: 'card-link' %>
          <%= link_to 'Back', admin_orders_path, class: 'card-link'  %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admin/orders/index.html.erb
<div class="container">

  <div class="row mt-3">

    <div class="col-md-10 mx-auto">

      <h3>Admin / Orders</h3>
      <hr>

      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <% Order.statuses.keys.each do |status| %>
            <a class="nav-item nav-link" id="nav-<%= status %>-tab" data-toggle="tab" href="#nav-<%= status %>" role="tab" aria-controls="nav-<%= status %>" aria-selected="false">
              <%= status.titleize %>
              <span class="badge badge-accent">
                <%= @orders.where(status: status).count %>
              </span>
            </a>
          <% end %>
        </div>
      </nav>

      <div class="tab-content" id="nav-tabContent">
        <% Order.statuses.keys.each do |status| %>
          <div class="tab-pane fade" id="nav-<%= status %>" role="tabpanel" aria-labelledby="nav-<%= status %>-tab">
            <% @orders.where(status: status).each do |order| %>
              <%= render(partial: 'orders/order', locals: {order: order}) ||
                      content_tag(:div, "There are no orders with this status right now.") %>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="row mt-3">

    <div class="col-lg-12">
      <div>
        <h3>Order Details</h3>

        <div class="d-flex flex-wrap">
          <div class="mr-5">Ordered
            on <%= @order.cart.paid_at.to_date.to_s(:long) %></div>
          <div>Order# <%= @order.id %></div>
        </div>
      </div>
      <hr>

      <p>
        For your receipt, check out the confirmation email our payment processor
        will send
        to <%= @order.user.email %>.
      </p>
      <p>
        Please call or whatsapp ProcureSwift on
        <a href="tel:+233541400077">(+233) 54 140 0077</a>
        with your reference number and name for an update on your order.
      </p>
      <p>
        Your reference number is: <strong><%= @order.txtref %></strong>
      </p>
      <hr>
    </div>


    <div class="col-lg-8">
      <%= render partial: 'carts/address_info_card', locals: {cart: @order.cart} %>

      <div class="card mb-4">
        <div class="card-body pb-2">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="card-title">Items</h5>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <% @order.cart.cart_items.order(created_at: :desc).each do |cart_item| %>
            <li class="list-group-item d-flex flex-column w-100 justify-content-start px-2">
              <a href="<%= product_path cart_item %>">
                <div class="d-flex w-100 justify-content-start">
                  <img class="product-image mr-2" src="<%= cart_item.main_image %>" width="100" style="height: 100px">
                  <div>
                    <h6 class="mb-2"><%= truncate cart_item.title, length: 60 %></h6>
                    <div class="text-danger ml-auto mb-2"><%= number_to_currency_gh dollar_to_cedi cart_item.unit_price %></div>
                    <div>Qty: <%= cart_item.quantity %></div>
                  </div>
                </div>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-lg-4">
      <%= render(layout: 'carts/costs_card', locals: {
          shippingCalculator: @shipping_cart
      }) do %>
        <%= link_to 'Edit', edit_admin_order_path(@order), class: 'btn btn-block btn-accent' %>
        <%= link_to 'Back', admin_orders_path, class: 'btn btn-block btn-info' %>
      <% end %>
    </div>

  </div>

</div>