config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  namespace :admin do
    resources :products
    resources :carts
    resources :orders
    resources :users
  end

  devise_for :users

  root 'welcome#index'

  resources :products
  resources :carts
  resources :cart_items
  resources :orders

  # static pages
  get '/privacy_policy', to: 'welcome#privacy_policy', as: :privacy_policy
  get '/terms', to: 'welcome#terms', as: :terms_and_conditions
  get '/refund_policy', to: 'welcome#refund_policy', as: :refund_policy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

# This does not inherit from ActiveRecord, but instead inherits from ActiveModel
class Product
  include ActiveModel::Model

  RETAILERS = {
    amazon: 0,
    amazon_uk: 1
  }.freeze

  RETAILER_PRODUCT_ID_SEPARATOR = '___'

  attr_accessor :product_id,
                :retailer,
                :title,
                :main_image,
                :price,
                :stars,
                :num_reviews,
                :weight,
                :width,
                :length,
                :depth,
                :offers,
                :product_description

  def self.find(id)
    retailer, product_id = split_retailer_from_product_id(id)

    product = Zinc.new.product_details(retailer, product_id)
    offers = Zinc.new.product_offers(retailer, product_id)

    product.offers = offers
    offers.each { |offer| offer.product = product }

    product
  end

  def self.where(query, retailer = 'amazon')
    Zinc.new.product_search(query, retailer)
  end

  def self.split_retailer_from_product_id(id)
    retailer, product_id = id.split(RETAILER_PRODUCT_ID_SEPARATOR)
    [retailer, product_id]
  end

  def self.merge_retailer_with_product_id(retailer, product_id)
    "#{retailer}#{RETAILER_PRODUCT_ID_SEPARATOR}#{product_id}"
  end

  def id
    Product.merge_retailer_with_product_id(retailer, product_id)
  end

  def item_url
    retailer, product_id = Product.split_retailer_from_product_id(id)
    case retailer
    when :amazon.to_s
      "https://www.amazon.com/dp/#{product_id}"
    when :amazon_uk.to_s
      "https://www.amazon.co.uk/dp/#{product_id}"
    else
      raise ArgumentError, 'retailer is invalid!'
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < AdminController
  before_action :set_product, only: %i[show]

  # GET /products
  def index
    @products = Product.where(query = params[:query],
                              retailer = params[:retailer])
  end

  # GET /products/1
  def show
    @offer = @product.offers.find { |offer| offer.id == params[:offer_id] } ||
        @product.offers.first
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  # GET /products
  def index
    session[:query] = params[:query]
    session[:retailer] = params[:retailer]
    @products = Product.where(query = params[:query],
                              retailer = params[:retailer])
  rescue Zinc::ZincError
    redirect_to root_path, alert: "Sorry, we couldn't connect to " \
                                  "#{params[:retailer].titleize} at this " \
                                  'time, please try again later.'
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])
    @offer = @product.offers.find { |offer| offer.id == params[:offer_id] } ||
             @product.offers.first
  rescue Zinc::ZincError
    retailer, _product_id = Product.split_retailer_from_product_id(params[:id])
    redirect_to root_path, alert: "Sorry, we couldn't connect to " \
                                  "#{retailer.titleize} at this time, " \
                                  'please try again later.'
  rescue Zinc::ZincArgumentError
    raise ActionController::RoutingError, "Sorry we couldn't find that page."
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= product.item_url %>
  </div>


  <div class="field">
    <%= truncate product.product_details_json.to_s %>
  </div>

  <div class="field">
    <%= truncate product.product_offers.to_s %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<div class="container-fluid">

  <div class="row mt-3">
    <div class="col-lg-12">
      <h3>Admin / Products</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-hover" id="products_table">
        <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Item url</th>
          <th scope="col">Zinc Product Details</th>
          <th  scope="col"></th>
          <th  scope="col"></th>
        </tr>
        </thead>

        <tbody>
        <% @products.each do |product| %>
          <tr>
            <td scope="row">
              <%= link_to product.id, admin_product_path(product) %>
            </td>
            <td>
              <%= truncate product.item_url %>
            </td>
            <td>
              <code>
                <%= truncate product.product_details_json.to_s, length: 100 %>
              </code>
            </td>
            <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
            <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<style>
  .container {
    max-width: 70rem;
  }
</style>

<div class="container">

  <div class="row mt-3">

    <div class="col-lg-4">
      <div class="card mb-3">
        <div class="card-body pb-0">
          <div class="h6 card-title mb-0">
            <%= @product.title %>
          </div>
        </div>

        <a href="<%= @product.item_url %>" target="_blank">
          <img src="<%= @product.main_image %>" class="card-img-top p-2 img-fluid" alt="...">
        </a>


        <div class="card-body">
          <div class="mb-4">
            <%= form_with(model: @product, local: false) do |form| %>
              <div class="form-group">
                <%= form.label :chosen_offer_id, "Price Offers" %>
                <%= form.collection_radio_buttons :chosen_offer_id,
                                                  collection = @product.offers,
                                                  value_method = :last,
                                                  text_method = :first,
                                                  options = {},
                                                  html_options = {} do |b| %>
                  <div class="form-check">
                    <%= b.radio_button class: "form-check-input", onclick: 'this.form.submit();' %>
                    <%= b.label class: "form-check-label", onclick: 'this.form.submit();' %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>

      </div>
    </div>

    <div class="col-lg-4 order-lg-3">
      <div class="card mb-3">
        <div class="card-body">
          <dl class="row mb-2">
            <dd class="col-8">Price:</dd>
            <dd class="col-4 text-right">
              <%= number_to_currency(@product.default_price) %>
            </dd>

            <dd class="col-8">Shipping & Insurance:</dd>
            <dd class="col-4 text-right">
              <%= number_to_currency @product.freight_insurance_handling %>
            </dd>

            <dd class="col-8 border-bottom">Estimated Duty:</dd>
            <dd class="col-4 text-right border-bottom">
              <%= number_to_currency @product.duty %>
            </dd>

            <dd class="col-6 text-truncate font-weight-bold text-danger">Total:</dd>
            <dd class="col-6 text-right font-weight-bold text-danger">
              <span id="order_total"><%= number_to_currency @product.total_cost %></span>
              <br>
              <span class="small">(<%= number_to_currency_gh dollar_to_cedi @product.total_cost %>)</span>
            </dd>
          </dl>


          <div class="mb-4">
            <div class="text-center">
              Will be delivered by
              <span class="text-success">
              <%= 2.weeks.from_now.strftime("%A, %b. %e") %>
              </span>
              <br>
              (2 weeks)
            </div>

            <div class="small text-center">
              Duty charges are subject to changes by customs.
            </div>
          </div>


          <div class="mb-4">
            <%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-block btn-accent' %>
            <%= link_to 'Delete Product', admin_product_path(@product), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-block btn-danger' %>
            <%= link_to 'Back', admin_products_path, class: 'btn btn-block btn-info' %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="card mb-3">
        <div class="card-body">
          <h6 class="card-title">
            Product Dimensions
          </h6>

          <div class="row mb-2">
            <div class="col-4">Width:</div>
            <div class="col-8 text-right">
              <%= number_with_precision @product.width, precision: 2 %>  <%= @product.width_unit %>
            </div>

            <div class="col-4">Length:</div>
            <div class="col-8 text-right">
              <%= number_with_precision @product.length, precision: 2 %> <%= @product.length_unit %>
            </div>

            <div class="col-4">Depth:</div>
            <div class="col-8 text-right">
              <%= number_with_precision @product.depth, precision: 2 %>  <%= @product.depth_unit %>
            </div>
          </div>

          <div class="row">
            <div class="col-4">Weight:</div>
            <div class="col-8 text-right">
              <%= number_with_precision @product.weight, precision: 2 %> pounds
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>