config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  namespace :admin do
    resources :products
    resources :carts
    resources :orders
    resources :users
  end

  devise_for :users

  root 'welcome#index'

  resources :products
  resources :carts
  resources :cart_items
  resources :orders

  # static pages
  get '/privacy_policy', to: 'welcome#privacy_policy', as: :privacy_policy
  get '/terms', to: 'welcome#terms', as: :terms_and_conditions
  get '/refund_policy', to: 'welcome#refund_policy', as: :refund_policy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?
  # The callback which stores the current location must be added before you authenticate the user
  # as `authenticate_user!` (or whatever your resource is) will halt the filter chain and redirect
  # before the location can be stored.

  before_action :authenticate_user!

  def current_cart
    if session[:cart_id]
      @current_cart ||= Cart.find(session[:cart_id])
      session[:cart_id] = nil if @current_cart.paid_at
    end
    create_cart if session[:cart_id].nil?
    @current_cart
  rescue ActiveRecord::RecordNotFound
    create_cart
  end

  helper_method :current_cart

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name phone_number])
  end

  private

  def create_cart
    @current_cart = Cart.create!(user: current_user)
    session[:cart_id] = @current_cart.id
    @current_cart
  end

  # Its important that the location is NOT stored if:
  # - The request method is not GET (non idempotent)
  # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
  #    infinite redirect loop.
  # - The request is an Ajax request as this can lead to very unexpected behaviour.
  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  DOLLAR_TO_CEDI_RATIO = 6.2

  def dollar_to_cedi(dollar_amount)
    dollar_amount * DOLLAR_TO_CEDI_RATIO
  end

  def number_to_currency_gh(amount)
    number_to_currency(amount, unit: 'GH₵ ')
  end

  def offer_choices(offers)
    offers.map do |offer|
      [
        offer['offer_id'],
        "#{number_to_currency(offer['price'])} #{offer['condition']}"
      ]
    end
  end
end

app/views/application/_footer.html.erb
<footer class="bg-primary pt-5 footer mt-auto">
  <div class="container">
    <div class="row">
      <div class="col-md-3 mb-2">
        <a href="<%= root_path %>">
          <%= image_tag "/img/Procurewift-17.png", height: "60", alt: "", style: "margin: -1.25rem" %>
        </a>
        <small class="d-block mb-2 text-muted">&copy; 2017 - <%= Date.today.year %></small>
      </div>
      <div class="col-md-3 mb-2">
        <h6 class="text-light">Let us help you</h6>
        <ul class="list-unstyled small">
          <!--<li><a class="text-muted" href="#">Partner us</a></li>
          <li><a class="text-muted" href="#">How it works</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>-->
          <li><a class="text-muted" href="<%= refund_policy_path %>">Refund and return policy</a></li>
          <!--<li><a class="text-muted" href="#">Corporate and bulk purchase</a></li>-->
        </ul>
      </div>
      <div class="col-md-3 mb-2">
        <h6 class="text-light">About ProcureSwift</h6>
        <ul class="list-unstyled small">
          <!--<li><a class="text-muted" href="#">Careers</a></li>
          <li><a class="text-muted" href="#">About Us</a></li>
          <li><a class="text-muted" href="#">Testimonials</a></li>-->
          <li><a class="text-muted" href="<%= privacy_policy_path %>">Privacy Policy</a></li>
          <li><a class="text-muted" href="<%= terms_and_conditions_path %>">Terms and Conditions</a></li>
        </ul>
      </div>
      <div class="col-md-3 mb-2">
        <h6 class="text-light">Contact Us</h6>
        <ul class="list-unstyled small">
          <li>
            <a class="text-muted" href="mailto:procureswift@buildpals.com">
              Email: procureswift@buildpals.com
            </a>
          </li>
          <li>
            <a class="text-muted" href="tel:+233541400077">
              Phone: +233 541400077
            </a>
          </li>
          <li>
            <a class="text-muted"
               href="https://www.google.com/maps/place/19+Banana+St,+Accra/@5.6453681,-0.1538217,17z"
               target="_blank">
              Address: 19 Banana Street, East Legon - Accra, Ghana
            </a>
          </li>
          <li class="mt-3">
            <a href="https://www.instagram.com/procureswift/" target="_blank">
              <i class="fab fa-instagram fa-2x fa-fw text-white"></i>
            </a>
            <a href="https://web.facebook.com/procureswift/" target="_blank">
              <i class="fab fa-facebook fa-2x fa-fw text-white"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/application/_search_bar.html.erb
<%= form_with(url: "/products", method: "get", local: true, class: 'form w-100') do %>
  <div class="input-group" data-toggle="modal" data-target="#searchModal">
    <%= text_field_tag :query,
                       session[:query] || "",
                       class: "form-control",
                       placeholder: 'Search products...' %>

    <div class="input-group-append">
      <%= button_tag(type: "submit", class: "btn btn-accent", data: {disable_with: 'Please wait...'}) do %>
        <span class="fa fa-search"></span>
      <% end %>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="form-group">
            <%= text_field_tag :query,
                               session[:query] || "",
                               class: "form-control",
                               placeholder: 'Search products...',
                               autofocus: true,
                               required: true %>

          </div>
          <div class="form-group">
            <% label_tag "retailer" %>
            <%= select_tag "retailer",
                           options_for_select(
                               Product::RETAILERS.keys.map {
                                   |r| [r.to_s.titleize, r]
                               },
                               selected = session[:retailer] || :amazon
                           ),
                           class: 'form-control' %>
          </div>

          <%= button_tag(type: "submit", class: "btn btn-block btn-accent", data: {disable_with: 'Please wait...'}) do %>
            Search
          <% end %>
        </div>

      </div>
    </div>
  </div>
<% end %>